//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgDefine.proto
namespace msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector2")]
  public partial class Vector2 : global::ProtoBuf.IExtensible
  {
    public Vector2() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    public Vector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogin")]
  public partial class ReqLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogin() {}
    
    private int _UseId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UseId
    {
      get { return _UseId; }
      set { _UseId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckLogin")]
  public partial class AckLogin : global::ProtoBuf.IExtensible
  {
    public AckLogin() {}
    
    private int _ErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ErrorCode
    {
      get { return _ErrorCode; }
      set { _ErrorCode = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _atk = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _def = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _hpMax = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private int _moveSpeed = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _modelClothes = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"modelClothes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int modelClothes
    {
      get { return _modelClothes; }
      set { _modelClothes = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEntryInfo")]
  public partial class PlayerEntryInfo : global::ProtoBuf.IExtensible
  {
    public PlayerEntryInfo() {}
    
    private int _object_guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"object_guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int object_guid
    {
      get { return _object_guid; }
      set { _object_guid = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private int _r = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"r", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int r
    {
      get { return _r; }
      set { _r = value; }
    }
    private msg.PlayerInfo _player_info;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public msg.PlayerInfo player_info
    {
      get { return _player_info; }
      set { _player_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckPlayerEntryList")]
  public partial class AckPlayerEntryList : global::ProtoBuf.IExtensible
  {
    public AckPlayerEntryList() {}
    
    private readonly global::System.Collections.Generic.List<msg.PlayerEntryInfo> _object_list = new global::System.Collections.Generic.List<msg.PlayerEntryInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"object_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.PlayerEntryInfo> object_list
    {
      get { return _object_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckPlayerLeaveList")]
  public partial class AckPlayerLeaveList : global::ProtoBuf.IExtensible
  {
    public AckPlayerLeaveList() {}
    
    private readonly global::System.Collections.Generic.List<int> _object_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"object_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> object_list
    {
      get { return _object_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckPublicPropertyList")]
  public partial class AckPublicPropertyList : global::ProtoBuf.IExtensible
  {
    public AckPublicPropertyList() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private msg.PlayerInfo _player_info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public msg.PlayerInfo player_info
    {
      get { return _player_info; }
      set { _player_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckSwapScene")]
  public partial class AckSwapScene : global::ProtoBuf.IExtensible
  {
    public AckSwapScene() {}
    
    private int _scene_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private int _r = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"r", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int r
    {
      get { return _r; }
      set { _r = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAckStop")]
  public partial class ReqAckStop : global::ProtoBuf.IExtensible
  {
    public ReqAckStop() {}
    
    private int _mover;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mover
    {
      get { return _mover; }
      set { _mover = value; }
    }
    private msg.Vector3 _source_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"source_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public msg.Vector3 source_pos
    {
      get { return _source_pos; }
      set { _source_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAckPlayerMove")]
  public partial class ReqAckPlayerMove : global::ProtoBuf.IExtensible
  {
    public ReqAckPlayerMove() {}
    
    private int _mover;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mover
    {
      get { return _mover; }
      set { _mover = value; }
    }
    private int _moveType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"moveType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveType
    {
      get { return _moveType; }
      set { _moveType = value; }
    }
    private readonly global::System.Collections.Generic.List<msg.Vector3> _target_pos = new global::System.Collections.Generic.List<msg.Vector3>();
    [global::ProtoBuf.ProtoMember(3, Name=@"target_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.Vector3> target_pos
    {
      get { return _target_pos; }
    }
  
    private readonly global::System.Collections.Generic.List<msg.Vector3> _source_pos = new global::System.Collections.Generic.List<msg.Vector3>();
    [global::ProtoBuf.ProtoMember(4, Name=@"source_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.Vector3> source_pos
    {
      get { return _source_pos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckSkillFail")]
  public partial class AckSkillFail : global::ProtoBuf.IExtensible
  {
    public AckSkillFail() {}
    
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private msg.UseSkillResult _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public msg.UseSkillResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckSkillStart")]
  public partial class AckSkillStart : global::ProtoBuf.IExtensible
  {
    public AckSkillStart() {}
    
    private int _caster;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"caster", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int caster
    {
      get { return _caster; }
      set { _caster = value; }
    }
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private int _dir = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DamageInfo")]
  public partial class DamageInfo : global::ProtoBuf.IExtensible
  {
    public DamageInfo() {}
    
    private int _target;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _flags;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flags
    {
      get { return _flags; }
      set { _flags = value; }
    }
    private int _leech = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"leech", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int leech
    {
      get { return _leech; }
      set { _leech = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillResult")]
  public partial class SkillResult : global::ProtoBuf.IExtensible
  {
    public SkillResult() {}
    
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private int _caster;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"caster", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int caster
    {
      get { return _caster; }
      set { _caster = value; }
    }
    private readonly global::System.Collections.Generic.List<msg.DamageInfo> _damages = new global::System.Collections.Generic.List<msg.DamageInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"damages", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.DamageInfo> damages
    {
      get { return _damages; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillStop")]
  public partial class SkillStop : global::ProtoBuf.IExtensible
  {
    public SkillStop() {}
    
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private int _caster;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"caster", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int caster
    {
      get { return _caster; }
      set { _caster = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"UseSkillResult")]
    public enum UseSkillResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_SUCCESS", Value=0)]
      CAST_SKILL_SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_NOT_EXIST", Value=1)]
      CAST_SKILL_NOT_EXIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_IN_CD", Value=2)]
      CAST_SKILL_IN_CD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_NOTENOUGH_HP", Value=3)]
      CAST_SKILL_NOTENOUGH_HP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_NOTENOUGH_MP", Value=4)]
      CAST_SKILL_NOTENOUGH_MP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_FAR_DISTANCE", Value=5)]
      CAST_SKILL_FAR_DISTANCE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_NO_TARGET", Value=6)]
      CAST_SKILL_NO_TARGET = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_DISABLED", Value=7)]
      CAST_SKILL_DISABLED = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_BAD_TARGET", Value=8)]
      CAST_SKILL_BAD_TARGET = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_CASTING", Value=9)]
      CAST_SKILL_CASTING = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAST_SKILL_UNKNOW_ERROR", Value=10)]
      CAST_SKILL_UNKNOW_ERROR = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DamageFlag")]
    public enum DamageFlag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAMAGE_FLAG_DODGE", Value=1)]
      DAMAGE_FLAG_DODGE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAMAGE_FLAG_PARRY", Value=2)]
      DAMAGE_FLAG_PARRY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAMAGE_FLAG_CRIT", Value=4)]
      DAMAGE_FLAG_CRIT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAMAGE_FLAG_WITHSTAND", Value=8)]
      DAMAGE_FLAG_WITHSTAND = 8
    }
  
}