//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgDefine.proto
namespace msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogin")]
  public partial class ReqLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogin() {}
    
    private int _UseId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UseId
    {
      get { return _UseId; }
      set { _UseId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckLogin")]
  public partial class AckLogin : global::ProtoBuf.IExtensible
  {
    public AckLogin() {}
    
    private int _ErrorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ErrorCode
    {
      get { return _ErrorCode; }
      set { _ErrorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}